//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

[assembly: PureLiveAssembly]
[assembly:ModelsBuilderAssembly(PureLive = true, SourceHash = "3c6fe13d9673fac6")]
[assembly:System.Reflection.AssemblyVersion("0.0.0.1")]

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Main PageDT</summary>
	[PublishedContentModel("mainPageDT")]
	public partial class MainPageDT : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "mainPageDT";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public MainPageDT(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<MainPageDT, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Banner
		///</summary>
		[ImplementPropertyType("banner")]
		public IPublishedContent Banner
		{
			get { return this.GetPropertyValue<IPublishedContent>("banner"); }
		}

		///<summary>
		/// Changed Texts
		///</summary>
		[ImplementPropertyType("changedTexts")]
		public IEnumerable<string> ChangedTexts
		{
			get { return this.GetPropertyValue<IEnumerable<string>>("changedTexts"); }
		}

		///<summary>
		/// Menu Title
		///</summary>
		[ImplementPropertyType("menuTitle")]
		public string MenuTitle
		{
			get { return this.GetPropertyValue<string>("menuTitle"); }
		}

		///<summary>
		/// Project Section Sub Title
		///</summary>
		[ImplementPropertyType("projectSectionSubTitle")]
		public string ProjectSectionSubTitle
		{
			get { return this.GetPropertyValue<string>("projectSectionSubTitle"); }
		}

		///<summary>
		/// Projects Section Title
		///</summary>
		[ImplementPropertyType("projectsSectionTitle")]
		public string ProjectsSectionTitle
		{
			get { return this.GetPropertyValue<string>("projectsSectionTitle"); }
		}

		///<summary>
		/// Services Section Picture
		///</summary>
		[ImplementPropertyType("servicesSectionPicture")]
		public IPublishedContent ServicesSectionPicture
		{
			get { return this.GetPropertyValue<IPublishedContent>("servicesSectionPicture"); }
		}

		///<summary>
		/// Services Section Title
		///</summary>
		[ImplementPropertyType("servicesSectionTitle")]
		public string ServicesSectionTitle
		{
			get { return this.GetPropertyValue<string>("servicesSectionTitle"); }
		}

		///<summary>
		/// Sub Title
		///</summary>
		[ImplementPropertyType("subTitle")]
		public string SubTitle
		{
			get { return this.GetPropertyValue<string>("subTitle"); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("title")]
		public string Title
		{
			get { return this.GetPropertyValue<string>("title"); }
		}
	}

	/// <summary>Main Page</summary>
	[PublishedContentModel("mainPage")]
	public partial class MainPage : Master
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "mainPage";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public MainPage(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<MainPage, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Email
		///</summary>
		[ImplementPropertyType("email")]
		public string Email
		{
			get { return this.GetPropertyValue<string>("email"); }
		}

		///<summary>
		/// Facebook
		///</summary>
		[ImplementPropertyType("facebook")]
		public string Facebook
		{
			get { return this.GetPropertyValue<string>("facebook"); }
		}

		///<summary>
		/// Instagram
		///</summary>
		[ImplementPropertyType("instagram")]
		public string Instagram
		{
			get { return this.GetPropertyValue<string>("instagram"); }
		}

		///<summary>
		/// LinkedIn
		///</summary>
		[ImplementPropertyType("linkedIn")]
		public string LinkedIn
		{
			get { return this.GetPropertyValue<string>("linkedIn"); }
		}

		///<summary>
		/// Main
		///</summary>
		[ImplementPropertyType("main")]
		public Our.Umbraco.Vorto.Models.VortoValue<IPublishedContent> Main
		{
			get { return this.GetPropertyValue<Our.Umbraco.Vorto.Models.VortoValue<IPublishedContent>>("main"); }
		}

		///<summary>
		/// Phone Number
		///</summary>
		[ImplementPropertyType("phoneNumber")]
		public string PhoneNumber
		{
			get { return this.GetPropertyValue<string>("phoneNumber"); }
		}

		///<summary>
		/// Slogans
		///</summary>
		[ImplementPropertyType("slogans")]
		public IEnumerable<IPublishedContent> Slogans
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("slogans"); }
		}

		///<summary>
		/// Telegram
		///</summary>
		[ImplementPropertyType("telegram")]
		public string Telegram
		{
			get { return this.GetPropertyValue<string>("telegram"); }
		}

		///<summary>
		/// Twitter
		///</summary>
		[ImplementPropertyType("twitter")]
		public string Twitter
		{
			get { return this.GetPropertyValue<string>("twitter"); }
		}

		///<summary>
		/// Seo Main
		///</summary>
		[ImplementPropertyType("seoMain")]
		public Our.Umbraco.Vorto.Models.VortoValue<Epiphany.SeoMetadata.SeoMetadata> SeoMain
		{
			get { return Umbraco.Web.PublishedContentModels.Master.GetSeoMain(this); }
		}

		///<summary>
		/// Url Preview
		///</summary>
		[ImplementPropertyType("urlPreview")]
		public object UrlPreview
		{
			get { return Umbraco.Web.PublishedContentModels.Master.GetUrlPreview(this); }
		}

		///<summary>
		/// Url Segment
		///</summary>
		[ImplementPropertyType("urlSegment")]
		public Our.Umbraco.Vorto.Models.VortoValue<string> UrlSegment
		{
			get { return Umbraco.Web.PublishedContentModels.Master.GetUrlSegment(this); }
		}
	}

	/// <summary>ContactDT</summary>
	[PublishedContentModel("contactDT")]
	public partial class ContactDT : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "contactDT";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ContactDT(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ContactDT, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Address
		///</summary>
		[ImplementPropertyType("address")]
		public string Address
		{
			get { return this.GetPropertyValue<string>("address"); }
		}

		///<summary>
		/// Banner
		///</summary>
		[ImplementPropertyType("banner")]
		public IPublishedContent Banner
		{
			get { return this.GetPropertyValue<IPublishedContent>("banner"); }
		}

		///<summary>
		/// Description
		///</summary>
		[ImplementPropertyType("description")]
		public IHtmlString Description
		{
			get { return this.GetPropertyValue<IHtmlString>("description"); }
		}

		///<summary>
		/// Email
		///</summary>
		[ImplementPropertyType("email")]
		public string Email
		{
			get { return this.GetPropertyValue<string>("email"); }
		}

		///<summary>
		/// Menu Title
		///</summary>
		[ImplementPropertyType("menuTitle")]
		public string MenuTitle
		{
			get { return this.GetPropertyValue<string>("menuTitle"); }
		}

		///<summary>
		/// Phone
		///</summary>
		[ImplementPropertyType("phone")]
		public string Phone
		{
			get { return this.GetPropertyValue<string>("phone"); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("title")]
		public string Title
		{
			get { return this.GetPropertyValue<string>("title"); }
		}
	}

	/// <summary>Contact</summary>
	[PublishedContentModel("contact")]
	public partial class Contact : Master
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "contact";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Contact(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Contact, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Main
		///</summary>
		[ImplementPropertyType("main")]
		public Our.Umbraco.Vorto.Models.VortoValue<IPublishedContent> Main
		{
			get { return this.GetPropertyValue<Our.Umbraco.Vorto.Models.VortoValue<IPublishedContent>>("main"); }
		}

		///<summary>
		/// Photo
		///</summary>
		[ImplementPropertyType("photo")]
		public IPublishedContent Photo
		{
			get { return this.GetPropertyValue<IPublishedContent>("photo"); }
		}

		///<summary>
		/// Seo Main
		///</summary>
		[ImplementPropertyType("seoMain")]
		public Our.Umbraco.Vorto.Models.VortoValue<Epiphany.SeoMetadata.SeoMetadata> SeoMain
		{
			get { return Umbraco.Web.PublishedContentModels.Master.GetSeoMain(this); }
		}

		///<summary>
		/// Url Preview
		///</summary>
		[ImplementPropertyType("urlPreview")]
		public object UrlPreview
		{
			get { return Umbraco.Web.PublishedContentModels.Master.GetUrlPreview(this); }
		}

		///<summary>
		/// Url Segment
		///</summary>
		[ImplementPropertyType("urlSegment")]
		public Our.Umbraco.Vorto.Models.VortoValue<string> UrlSegment
		{
			get { return Umbraco.Web.PublishedContentModels.Master.GetUrlSegment(this); }
		}
	}

	// Mixin content Type 1085 with alias "master"
	/// <summary>Master</summary>
	public partial interface IMaster : IPublishedContent
	{
		/// <summary>Seo Main</summary>
		Our.Umbraco.Vorto.Models.VortoValue<Epiphany.SeoMetadata.SeoMetadata> SeoMain { get; }

		/// <summary>Url Preview</summary>
		object UrlPreview { get; }

		/// <summary>Url Segment</summary>
		Our.Umbraco.Vorto.Models.VortoValue<string> UrlSegment { get; }
	}

	/// <summary>Master</summary>
	[PublishedContentModel("master")]
	public partial class Master : PublishedContentModel, IMaster
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "master";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Master(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Master, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Seo Main
		///</summary>
		[ImplementPropertyType("seoMain")]
		public Our.Umbraco.Vorto.Models.VortoValue<Epiphany.SeoMetadata.SeoMetadata> SeoMain
		{
			get { return GetSeoMain(this); }
		}

		/// <summary>Static getter for Seo Main</summary>
		public static Our.Umbraco.Vorto.Models.VortoValue<Epiphany.SeoMetadata.SeoMetadata> GetSeoMain(IMaster that) { return that.GetPropertyValue<Our.Umbraco.Vorto.Models.VortoValue<Epiphany.SeoMetadata.SeoMetadata>>("seoMain"); }

		///<summary>
		/// Url Preview
		///</summary>
		[ImplementPropertyType("urlPreview")]
		public object UrlPreview
		{
			get { return GetUrlPreview(this); }
		}

		/// <summary>Static getter for Url Preview</summary>
		public static object GetUrlPreview(IMaster that) { return that.GetPropertyValue("urlPreview"); }

		///<summary>
		/// Url Segment
		///</summary>
		[ImplementPropertyType("urlSegment")]
		public Our.Umbraco.Vorto.Models.VortoValue<string> UrlSegment
		{
			get { return GetUrlSegment(this); }
		}

		/// <summary>Static getter for Url Segment</summary>
		public static Our.Umbraco.Vorto.Models.VortoValue<string> GetUrlSegment(IMaster that) { return that.GetPropertyValue<Our.Umbraco.Vorto.Models.VortoValue<string>>("urlSegment"); }
	}

	/// <summary>Title Description Feature</summary>
	[PublishedContentModel("titleDescriptionFeature")]
	public partial class TitleDescriptionFeature : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "titleDescriptionFeature";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public TitleDescriptionFeature(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<TitleDescriptionFeature, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Main
		///</summary>
		[ImplementPropertyType("main")]
		public Our.Umbraco.Vorto.Models.VortoValue<IPublishedContent> Main
		{
			get { return this.GetPropertyValue<Our.Umbraco.Vorto.Models.VortoValue<IPublishedContent>>("main"); }
		}
	}

	/// <summary>Title Description FeatureDT</summary>
	[PublishedContentModel("titleDescriptionFeatureDT")]
	public partial class TitleDescriptionFeatureDT : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "titleDescriptionFeatureDT";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public TitleDescriptionFeatureDT(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<TitleDescriptionFeatureDT, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Description
		///</summary>
		[ImplementPropertyType("description")]
		public IHtmlString Description
		{
			get { return this.GetPropertyValue<IHtmlString>("description"); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("title")]
		public string Title
		{
			get { return this.GetPropertyValue<string>("title"); }
		}
	}

	/// <summary>ProjectsDT</summary>
	[PublishedContentModel("projectsDT")]
	public partial class ProjectsDT : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "projectsDT";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ProjectsDT(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ProjectsDT, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Banner
		///</summary>
		[ImplementPropertyType("banner")]
		public IPublishedContent Banner
		{
			get { return this.GetPropertyValue<IPublishedContent>("banner"); }
		}

		///<summary>
		/// Sub Title
		///</summary>
		[ImplementPropertyType("subTitle")]
		public string SubTitle
		{
			get { return this.GetPropertyValue<string>("subTitle"); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("title")]
		public string Title
		{
			get { return this.GetPropertyValue<string>("title"); }
		}
	}

	/// <summary>Projects</summary>
	[PublishedContentModel("projects")]
	public partial class Projects : Master
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "projects";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Projects(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Projects, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Main
		///</summary>
		[ImplementPropertyType("main")]
		public Our.Umbraco.Vorto.Models.VortoValue<IPublishedContent> Main
		{
			get { return this.GetPropertyValue<Our.Umbraco.Vorto.Models.VortoValue<IPublishedContent>>("main"); }
		}

		///<summary>
		/// Seo Main
		///</summary>
		[ImplementPropertyType("seoMain")]
		public Our.Umbraco.Vorto.Models.VortoValue<Epiphany.SeoMetadata.SeoMetadata> SeoMain
		{
			get { return Umbraco.Web.PublishedContentModels.Master.GetSeoMain(this); }
		}

		///<summary>
		/// Url Preview
		///</summary>
		[ImplementPropertyType("urlPreview")]
		public object UrlPreview
		{
			get { return Umbraco.Web.PublishedContentModels.Master.GetUrlPreview(this); }
		}

		///<summary>
		/// Url Segment
		///</summary>
		[ImplementPropertyType("urlSegment")]
		public Our.Umbraco.Vorto.Models.VortoValue<string> UrlSegment
		{
			get { return Umbraco.Web.PublishedContentModels.Master.GetUrlSegment(this); }
		}
	}

	/// <summary>ProjectDT</summary>
	[PublishedContentModel("projectDT")]
	public partial class ProjectDT : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "projectDT";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ProjectDT(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ProjectDT, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Description
		///</summary>
		[ImplementPropertyType("description")]
		public IHtmlString Description
		{
			get { return this.GetPropertyValue<IHtmlString>("description"); }
		}

		///<summary>
		/// Main Photo
		///</summary>
		[ImplementPropertyType("mainPhoto")]
		public IPublishedContent MainPhoto
		{
			get { return this.GetPropertyValue<IPublishedContent>("mainPhoto"); }
		}

		///<summary>
		/// Photos
		///</summary>
		[ImplementPropertyType("photos")]
		public IEnumerable<IPublishedContent> Photos
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("photos"); }
		}

		///<summary>
		/// Show In Main Page
		///</summary>
		[ImplementPropertyType("showInMainPage")]
		public bool ShowInMainPage
		{
			get { return this.GetPropertyValue<bool>("showInMainPage"); }
		}

		///<summary>
		/// Sub Title
		///</summary>
		[ImplementPropertyType("subTitle")]
		public string SubTitle
		{
			get { return this.GetPropertyValue<string>("subTitle"); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("title")]
		public string Title
		{
			get { return this.GetPropertyValue<string>("title"); }
		}
	}

	/// <summary>Project</summary>
	[PublishedContentModel("project")]
	public partial class Project : Master
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "project";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Project(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Project, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Main
		///</summary>
		[ImplementPropertyType("main")]
		public Our.Umbraco.Vorto.Models.VortoValue<IPublishedContent> Main
		{
			get { return this.GetPropertyValue<Our.Umbraco.Vorto.Models.VortoValue<IPublishedContent>>("main"); }
		}

		///<summary>
		/// Seo Main
		///</summary>
		[ImplementPropertyType("seoMain")]
		public Our.Umbraco.Vorto.Models.VortoValue<Epiphany.SeoMetadata.SeoMetadata> SeoMain
		{
			get { return Umbraco.Web.PublishedContentModels.Master.GetSeoMain(this); }
		}

		///<summary>
		/// Url Preview
		///</summary>
		[ImplementPropertyType("urlPreview")]
		public object UrlPreview
		{
			get { return Umbraco.Web.PublishedContentModels.Master.GetUrlPreview(this); }
		}

		///<summary>
		/// Url Segment
		///</summary>
		[ImplementPropertyType("urlSegment")]
		public Our.Umbraco.Vorto.Models.VortoValue<string> UrlSegment
		{
			get { return Umbraco.Web.PublishedContentModels.Master.GetUrlSegment(this); }
		}
	}

	/// <summary>ServicesDT</summary>
	[PublishedContentModel("servicesDT")]
	public partial class ServicesDT : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "servicesDT";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ServicesDT(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ServicesDT, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Banner
		///</summary>
		[ImplementPropertyType("banner")]
		public IPublishedContent Banner
		{
			get { return this.GetPropertyValue<IPublishedContent>("banner"); }
		}

		///<summary>
		/// Menu Title
		///</summary>
		[ImplementPropertyType("menuTitle")]
		public string MenuTitle
		{
			get { return this.GetPropertyValue<string>("menuTitle"); }
		}

		///<summary>
		/// Sub Title
		///</summary>
		[ImplementPropertyType("subTitle")]
		public string SubTitle
		{
			get { return this.GetPropertyValue<string>("subTitle"); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("title")]
		public string Title
		{
			get { return this.GetPropertyValue<string>("title"); }
		}
	}

	/// <summary>Services</summary>
	[PublishedContentModel("services")]
	public partial class Services : Master
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "services";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Services(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Services, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Main
		///</summary>
		[ImplementPropertyType("main")]
		public Our.Umbraco.Vorto.Models.VortoValue<IPublishedContent> Main
		{
			get { return this.GetPropertyValue<Our.Umbraco.Vorto.Models.VortoValue<IPublishedContent>>("main"); }
		}

		///<summary>
		/// Seo Main
		///</summary>
		[ImplementPropertyType("seoMain")]
		public Our.Umbraco.Vorto.Models.VortoValue<Epiphany.SeoMetadata.SeoMetadata> SeoMain
		{
			get { return Umbraco.Web.PublishedContentModels.Master.GetSeoMain(this); }
		}

		///<summary>
		/// Url Preview
		///</summary>
		[ImplementPropertyType("urlPreview")]
		public object UrlPreview
		{
			get { return Umbraco.Web.PublishedContentModels.Master.GetUrlPreview(this); }
		}

		///<summary>
		/// Url Segment
		///</summary>
		[ImplementPropertyType("urlSegment")]
		public Our.Umbraco.Vorto.Models.VortoValue<string> UrlSegment
		{
			get { return Umbraco.Web.PublishedContentModels.Master.GetUrlSegment(this); }
		}
	}

	/// <summary>ServiceDT</summary>
	[PublishedContentModel("serviceDT")]
	public partial class ServiceDT : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "serviceDT";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ServiceDT(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ServiceDT, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Description
		///</summary>
		[ImplementPropertyType("description")]
		public IHtmlString Description
		{
			get { return this.GetPropertyValue<IHtmlString>("description"); }
		}

		///<summary>
		/// Icon
		///</summary>
		[ImplementPropertyType("icon")]
		public IPublishedContent Icon
		{
			get { return this.GetPropertyValue<IPublishedContent>("icon"); }
		}

		///<summary>
		/// Menu Title
		///</summary>
		[ImplementPropertyType("menuTitle")]
		public string MenuTitle
		{
			get { return this.GetPropertyValue<string>("menuTitle"); }
		}

		///<summary>
		/// Sub Title
		///</summary>
		[ImplementPropertyType("subTitle")]
		public string SubTitle
		{
			get { return this.GetPropertyValue<string>("subTitle"); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("title")]
		public string Title
		{
			get { return this.GetPropertyValue<string>("title"); }
		}
	}

	/// <summary>Service</summary>
	[PublishedContentModel("service")]
	public partial class Service : Master
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "service";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Service(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Service, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Main
		///</summary>
		[ImplementPropertyType("main")]
		public Our.Umbraco.Vorto.Models.VortoValue<IPublishedContent> Main
		{
			get { return this.GetPropertyValue<Our.Umbraco.Vorto.Models.VortoValue<IPublishedContent>>("main"); }
		}

		///<summary>
		/// Seo Main
		///</summary>
		[ImplementPropertyType("seoMain")]
		public Our.Umbraco.Vorto.Models.VortoValue<Epiphany.SeoMetadata.SeoMetadata> SeoMain
		{
			get { return Umbraco.Web.PublishedContentModels.Master.GetSeoMain(this); }
		}

		///<summary>
		/// Url Preview
		///</summary>
		[ImplementPropertyType("urlPreview")]
		public object UrlPreview
		{
			get { return Umbraco.Web.PublishedContentModels.Master.GetUrlPreview(this); }
		}

		///<summary>
		/// Url Segment
		///</summary>
		[ImplementPropertyType("urlSegment")]
		public Our.Umbraco.Vorto.Models.VortoValue<string> UrlSegment
		{
			get { return Umbraco.Web.PublishedContentModels.Master.GetUrlSegment(this); }
		}
	}

	/// <summary>AboutDT</summary>
	[PublishedContentModel("aboutDT")]
	public partial class AboutDT : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "aboutDT";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public AboutDT(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<AboutDT, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// About Us Title
		///</summary>
		[ImplementPropertyType("aboutUsTitle")]
		public string AboutUsTitle
		{
			get { return this.GetPropertyValue<string>("aboutUsTitle"); }
		}

		///<summary>
		/// Banner
		///</summary>
		[ImplementPropertyType("banner")]
		public IPublishedContent Banner
		{
			get { return this.GetPropertyValue<IPublishedContent>("banner"); }
		}

		///<summary>
		/// Menu Title
		///</summary>
		[ImplementPropertyType("menuTitle")]
		public string MenuTitle
		{
			get { return this.GetPropertyValue<string>("menuTitle"); }
		}

		///<summary>
		/// Photo
		///</summary>
		[ImplementPropertyType("photo")]
		public IPublishedContent Photo
		{
			get { return this.GetPropertyValue<IPublishedContent>("photo"); }
		}

		///<summary>
		/// Sub Title
		///</summary>
		[ImplementPropertyType("subTitle")]
		public string SubTitle
		{
			get { return this.GetPropertyValue<string>("subTitle"); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("title")]
		public string Title
		{
			get { return this.GetPropertyValue<string>("title"); }
		}
	}

	/// <summary>About</summary>
	[PublishedContentModel("about")]
	public partial class About : Master
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "about";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public About(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<About, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// About Us Items
		///</summary>
		[ImplementPropertyType("aboutUsItems")]
		public IEnumerable<IPublishedContent> AboutUsItems
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("aboutUsItems"); }
		}

		///<summary>
		/// Main
		///</summary>
		[ImplementPropertyType("main")]
		public Our.Umbraco.Vorto.Models.VortoValue<IPublishedContent> Main
		{
			get { return this.GetPropertyValue<Our.Umbraco.Vorto.Models.VortoValue<IPublishedContent>>("main"); }
		}

		///<summary>
		/// Team Members
		///</summary>
		[ImplementPropertyType("teamMembers")]
		public IEnumerable<IPublishedContent> TeamMembers
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("teamMembers"); }
		}

		///<summary>
		/// Seo Main
		///</summary>
		[ImplementPropertyType("seoMain")]
		public Our.Umbraco.Vorto.Models.VortoValue<Epiphany.SeoMetadata.SeoMetadata> SeoMain
		{
			get { return Umbraco.Web.PublishedContentModels.Master.GetSeoMain(this); }
		}

		///<summary>
		/// Url Preview
		///</summary>
		[ImplementPropertyType("urlPreview")]
		public object UrlPreview
		{
			get { return Umbraco.Web.PublishedContentModels.Master.GetUrlPreview(this); }
		}

		///<summary>
		/// Url Segment
		///</summary>
		[ImplementPropertyType("urlSegment")]
		public Our.Umbraco.Vorto.Models.VortoValue<string> UrlSegment
		{
			get { return Umbraco.Web.PublishedContentModels.Master.GetUrlSegment(this); }
		}
	}

	/// <summary>About UsDT</summary>
	[PublishedContentModel("aboutUsDT")]
	public partial class AboutUsDT : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "aboutUsDT";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public AboutUsDT(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<AboutUsDT, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Icon
		///</summary>
		[ImplementPropertyType("icon")]
		public IPublishedContent Icon
		{
			get { return this.GetPropertyValue<IPublishedContent>("icon"); }
		}

		///<summary>
		/// Sub Title
		///</summary>
		[ImplementPropertyType("subTitle")]
		public string SubTitle
		{
			get { return this.GetPropertyValue<string>("subTitle"); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("title")]
		public string Title
		{
			get { return this.GetPropertyValue<string>("title"); }
		}
	}

	/// <summary>About Us</summary>
	[PublishedContentModel("aboutUs")]
	public partial class AboutUs : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "aboutUs";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public AboutUs(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<AboutUs, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Main
		///</summary>
		[ImplementPropertyType("main")]
		public Our.Umbraco.Vorto.Models.VortoValue<IPublishedContent> Main
		{
			get { return this.GetPropertyValue<Our.Umbraco.Vorto.Models.VortoValue<IPublishedContent>>("main"); }
		}
	}

	/// <summary>TeamDT</summary>
	[PublishedContentModel("teamDT")]
	public partial class TeamDT : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "teamDT";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public TeamDT(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<TeamDT, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Description
		///</summary>
		[ImplementPropertyType("description")]
		public IHtmlString Description
		{
			get { return this.GetPropertyValue<IHtmlString>("description"); }
		}

		///<summary>
		/// Facebook
		///</summary>
		[ImplementPropertyType("facebook")]
		public string Facebook
		{
			get { return this.GetPropertyValue<string>("facebook"); }
		}

		///<summary>
		/// Full Name
		///</summary>
		[ImplementPropertyType("fullName")]
		public string FullName
		{
			get { return this.GetPropertyValue<string>("fullName"); }
		}

		///<summary>
		/// Instagram
		///</summary>
		[ImplementPropertyType("instagram")]
		public string Instagram
		{
			get { return this.GetPropertyValue<string>("instagram"); }
		}

		///<summary>
		/// Job
		///</summary>
		[ImplementPropertyType("job")]
		public string Job
		{
			get { return this.GetPropertyValue<string>("job"); }
		}

		///<summary>
		/// LinkedIn
		///</summary>
		[ImplementPropertyType("linkedIn")]
		public string LinkedIn
		{
			get { return this.GetPropertyValue<string>("linkedIn"); }
		}

		///<summary>
		/// Photo
		///</summary>
		[ImplementPropertyType("photo")]
		public IPublishedContent Photo
		{
			get { return this.GetPropertyValue<IPublishedContent>("photo"); }
		}

		///<summary>
		/// Twitter
		///</summary>
		[ImplementPropertyType("twitter")]
		public string Twitter
		{
			get { return this.GetPropertyValue<string>("twitter"); }
		}
	}

	/// <summary>Team</summary>
	[PublishedContentModel("team")]
	public partial class Team : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "team";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Team(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Team, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Main
		///</summary>
		[ImplementPropertyType("main")]
		public Our.Umbraco.Vorto.Models.VortoValue<IPublishedContent> Main
		{
			get { return this.GetPropertyValue<Our.Umbraco.Vorto.Models.VortoValue<IPublishedContent>>("main"); }
		}
	}

	/// <summary>Folder</summary>
	[PublishedContentModel("Folder")]
	public partial class Folder : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Folder";
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
#pragma warning restore 0109

		public Folder(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Folder, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Contents:
		///</summary>
		[ImplementPropertyType("contents")]
		public object Contents
		{
			get { return this.GetPropertyValue("contents"); }
		}
	}

	/// <summary>Image</summary>
	[PublishedContentModel("Image")]
	public partial class Image : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Image";
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
#pragma warning restore 0109

		public Image(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Image, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Size
		///</summary>
		[ImplementPropertyType("umbracoBytes")]
		public string UmbracoBytes
		{
			get { return this.GetPropertyValue<string>("umbracoBytes"); }
		}

		///<summary>
		/// Type
		///</summary>
		[ImplementPropertyType("umbracoExtension")]
		public string UmbracoExtension
		{
			get { return this.GetPropertyValue<string>("umbracoExtension"); }
		}

		///<summary>
		/// Upload image
		///</summary>
		[ImplementPropertyType("umbracoFile")]
		public Umbraco.Web.Models.ImageCropDataSet UmbracoFile
		{
			get { return this.GetPropertyValue<Umbraco.Web.Models.ImageCropDataSet>("umbracoFile"); }
		}

		///<summary>
		/// Height
		///</summary>
		[ImplementPropertyType("umbracoHeight")]
		public string UmbracoHeight
		{
			get { return this.GetPropertyValue<string>("umbracoHeight"); }
		}

		///<summary>
		/// Width
		///</summary>
		[ImplementPropertyType("umbracoWidth")]
		public string UmbracoWidth
		{
			get { return this.GetPropertyValue<string>("umbracoWidth"); }
		}
	}

	/// <summary>File</summary>
	[PublishedContentModel("File")]
	public partial class File : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "File";
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
#pragma warning restore 0109

		public File(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<File, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Size
		///</summary>
		[ImplementPropertyType("umbracoBytes")]
		public string UmbracoBytes
		{
			get { return this.GetPropertyValue<string>("umbracoBytes"); }
		}

		///<summary>
		/// Type
		///</summary>
		[ImplementPropertyType("umbracoExtension")]
		public string UmbracoExtension
		{
			get { return this.GetPropertyValue<string>("umbracoExtension"); }
		}

		///<summary>
		/// Upload file
		///</summary>
		[ImplementPropertyType("umbracoFile")]
		public string UmbracoFile
		{
			get { return this.GetPropertyValue<string>("umbracoFile"); }
		}
	}

	/// <summary>Member</summary>
	[PublishedContentModel("Member")]
	public partial class Member : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Member";
		public new const PublishedItemType ModelItemType = PublishedItemType.Member;
#pragma warning restore 0109

		public Member(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Member, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Is Approved
		///</summary>
		[ImplementPropertyType("umbracoMemberApproved")]
		public bool UmbracoMemberApproved
		{
			get { return this.GetPropertyValue<bool>("umbracoMemberApproved"); }
		}

		///<summary>
		/// Comments
		///</summary>
		[ImplementPropertyType("umbracoMemberComments")]
		public string UmbracoMemberComments
		{
			get { return this.GetPropertyValue<string>("umbracoMemberComments"); }
		}

		///<summary>
		/// Failed Password Attempts
		///</summary>
		[ImplementPropertyType("umbracoMemberFailedPasswordAttempts")]
		public string UmbracoMemberFailedPasswordAttempts
		{
			get { return this.GetPropertyValue<string>("umbracoMemberFailedPasswordAttempts"); }
		}

		///<summary>
		/// Last Lockout Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastLockoutDate")]
		public string UmbracoMemberLastLockoutDate
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastLockoutDate"); }
		}

		///<summary>
		/// Last Login Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastLogin")]
		public string UmbracoMemberLastLogin
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastLogin"); }
		}

		///<summary>
		/// Last Password Change Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastPasswordChangeDate")]
		public string UmbracoMemberLastPasswordChangeDate
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastPasswordChangeDate"); }
		}

		///<summary>
		/// Is Locked Out
		///</summary>
		[ImplementPropertyType("umbracoMemberLockedOut")]
		public bool UmbracoMemberLockedOut
		{
			get { return this.GetPropertyValue<bool>("umbracoMemberLockedOut"); }
		}

		///<summary>
		/// Password Answer
		///</summary>
		[ImplementPropertyType("umbracoMemberPasswordRetrievalAnswer")]
		public string UmbracoMemberPasswordRetrievalAnswer
		{
			get { return this.GetPropertyValue<string>("umbracoMemberPasswordRetrievalAnswer"); }
		}

		///<summary>
		/// Password Question
		///</summary>
		[ImplementPropertyType("umbracoMemberPasswordRetrievalQuestion")]
		public string UmbracoMemberPasswordRetrievalQuestion
		{
			get { return this.GetPropertyValue<string>("umbracoMemberPasswordRetrievalQuestion"); }
		}
	}

}
